apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "0 1 * * *"  # This CronJob runs at 01:00 AM every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: back-up-service
            image: back-up-service:latest
            ports:
            - containerPort: 80
            volumeMounts:
            - name: backup-volume
              mountPath: /usr/src/app/files
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            hostPath:
              path: "/mnt/data/A/6th sem/CC/miniproject/Back-Up-service/backup"
              type: DirectoryOrCreate
